name: Go

on:
  push:
    branches: [ master, /^Feature/.*$/ ]
  pull_request:
    branches: [ master, /^Feature/.*$/ ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test -v ./cmd/d2twitch

    - name: Lint
      run: go get -u golang.org/x/lint/golint && golint ./cmd/d2twitch

    - name: Build
      run: |
      go build -v -o bin/d2twitch ./...
      GOOS=windows go build -v -o bin/D2twitch.exe ./cmd/d2twitch

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: "bin/*.tgz"