name: Go

on:
  push:
    branches: [ master, /^Feature/.*$/ ]
  pull_request:
    branches: [ master, /^Feature/.*$/ ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test -v ./...

    - name: Shows Avail Dists
      run: go tool dist list

    - name: Build
      run: go build -v -o bin/D2Twitch ./...