name: Go

on:
  push:
    branches: [ master, /^Feature/.*$/ ]
  pull_request:
    branches: [ master, /^Feature/.*$/ ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test -v ./cmd/D2Twitch

    - name: Lint
      run: go get -u golang.org/x/lint/golint && golint ./cmd/D2Twitch