name: Upload Release Asseton

on:
  push:
    tags:
      - 'V*'

jobs:
  build:

    name: Upload Release Asset
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build Linux
        run: |
          rm -rf bin/linux/*
          go build -v -o bin/linux/d2twitch ./cmd/D2Twitch
          cp config/config.yml bin/linux/config.yml

      - name: Build Windows
        run: |
          rm -rf bin/windows/*
          GOOS=windows go build -v -o bin/windows/D2twitch.exe ./cmd/D2Twitch
          cp config/config.yaml bin/windows/config.yml

      - name: Zip Linux
        uses: papeloto/action-zip@v1
        with:
          files: bin/linux/
          dest: d2twitch-linux.zip

      - name: Zip Windows
        uses: papeloto/action-zip@v1
        with:
          files: bin/windows/
          dest: d2twitch-windows.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Linux Asset
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .bin/d2twitch-linux.zip
          asset_name: d2twitch-linux.zip
          asset_content_type: application/zip

      - name: Upload Release Windows Asset
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .bin/d2twitch-windows.zip
          asset_name: d2twitch-windows.zip
          asset_content_type: application/zip